Support StringTensor as model output in Neuropod JNI
uber/neuropod pull request #515
Opened 2021-11-04 23:08 UTC by voe09

### Summary:
In neuropod JNI, it does not support STRING_TENSOR as model output. The reason is when it tries to create a Java Tensor from model output, it would check the tensor type. Only numerical tensors are supported and these tensors would be converted to ByteBuffer. However, Java NeuropodTensor itself do support STRING_TENSOR. It can get strings from the tensor data itself. Thus we refactor nativeGetBuffer method. This method would assign a null buffer to bytebuffer if it is a string tensor

### Test Plan:
Unit test

2021-11-04 23:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/neuropod?pullRequest=515) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/neuropod?pullRequest=515) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/neuropod?pullRequest=515) it.</sub>

2021-11-05 18:02 UTC, qiyanz approved these changes

2021-11-05 20:13 UTC, VivekPanyam requested changes
Thanks for the PR! Looks good overall.

I left one comment that needs to be fixed in order for CI to pass. Once CI passes, I'll go ahead and merge the PR. Thanks again!

2021-11-05 20:13 UTC, VivekPanyam commented on source/neuropod/bindings/java/BUILD
> +    tags = ["requires_framework_tensorflow"],
Replace with `requires_framework_torchscript`

2021-11-05 21:05 UTC, voe09 commented on source/neuropod/bindings/java/BUILD
> +    tags = ["requires_framework_tensorflow"],
Thanks @VivekPanyam I've updated my pr.

2021-11-17 06:01 UTC, voe09 commented
Hi @VivekPanyam could you help take a look at the diff. I have rebased the master branch and all CI passed. Thanks!

2021-11-17 06:03 UTC, VivekPanyam commented
None of the Linux CI has passed yet, but just unblocked it so it should be running now

2021-11-17 07:59 UTC, VivekPanyam approved these changes
LGTM!

2021-11-17 07:59 UTC, merged